# Generated by Django 4.1.13 on 2024-05-29 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Base'), (2, 'Sauce'), (3, 'Cheese'), (4, 'Veggies')])),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('decription', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(height_field='100', null=True, upload_to='pizza_images', width_field='100')),
                ('pizza_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pizza_b', to='pizzaDelivery.pizzaitems')),
                ('pizza_cheese', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pizza_c', to='pizzaDelivery.pizzaitems')),
                ('pizza_sauce', models.ManyToManyField(related_name='pizza_s', to='pizzaDelivery.pizzaitems')),
                ('pizza_veggies', models.ManyToManyField(related_name='pizza_v', to='pizzaDelivery.pizzaitems')),
            ],
        ),
    ]
