# Generated by Django 4.1.13 on 2024-05-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaDelivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzaVeggie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='pizza_veggies',
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_veggie',
            field=models.ManyToManyField(related_name='pizza_v', to='pizzaDelivery.pizzaveggie'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pizza_b', to='pizzaDelivery.pizzabase'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_cheese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pizza_c', to='pizzaDelivery.pizzacheese'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_sauce',
            field=models.ManyToManyField(related_name='pizza_s', to='pizzaDelivery.pizzasauce'),
        ),
        migrations.DeleteModel(
            name='PizzaItems',
        ),
    ]
