# Generated by Django 4.1.13 on 2024-05-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaDelivery', '0002_pizzabase_pizzacheese_pizzasauce_pizzaveggie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzasauce',
            name='quantity',
        ),
        migrations.AddField(
            model_name='pizzasauce',
            name='description',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizzasauce',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, height_field='100', null=True, upload_to='pizza_images', width_field='100'),
        ),
    ]
