# Generated by Django 4.1.13 on 2024-05-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaDelivery', '0003_remove_pizzasauce_quantity_pizzasauce_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzasauce',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
