# Generated by Django 4.1.13 on 2024-06-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaDelivery', '0011_alter_customer_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
