# Generated by Django 4.1.13 on 2024-06-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaDelivery', '0012_customer_city_customer_country_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
