# Generated by Django 4.1.13 on 2024-06-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaDelivery', '0015_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('C', 'Cooking'), ('O', 'Out for Delivery'), ('D', 'Delevered')], max_length=255, null=True),
        ),
    ]
