# Generated by Django 4.1.13 on 2024-06-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaDelivery', '0016_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
