# Generated by Django 4.1.13 on 2024-06-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaDelivery', '0017_pizza_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='decription',
            field=models.TextField(null=True),
        ),
    ]
