# Generated by Django 4.1.13 on 2024-06-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaDelivery', '0018_alter_pizza_decription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzasauce',
            name='description',
        ),
    ]
