# Generated by Django 4.1.13 on 2024-05-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verfied',
            field=models.BooleanField(default=False),
        ),
    ]
