# Generated by Django 4.1.13 on 2024-05-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_user_verfied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
